import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import GlobalLoader from "@/components/GlobalLoader.client";
import { cn } from "@/lib/utils";
import AuthRehydrator from "@/components/AuthRehydrator.client";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen flex flex-col",
					geistSans,
					geistMono
				)}
			>
				<Providers>
					<GlobalLoader loading={false} />
					<AuthRehydrator />
					<Header />
					<main className="flex-grow">{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
